FROM node:16 as base

WORKDIR /home/node/app
COPY package*.json ./

FROM base as test
RUN npm ci
COPY . .
RUN apt-get update && \ 
  apt-get -y dist-upgrade && \
  apt-get install -y postgresql-client && \
  sh -c 'env' && \
  sh -c 'chmod 755 entrypoint.test.sh'
VOLUME [ "/home/node/app/logs" ]